Multiple source directories code review
NoRedInk/find-elm-dependencies pull request #3
Opened 2017-03-25 06:54 UTC by sentience

Code quality improvements following post-merge comments on NoRedInk/find-elm-dependencies#1 (thanks again, @eeue56!).

2017-03-27 23:28 UTC, sentience commented
@eeue56 Just making sure this is on your radar.

2017-03-28 08:35 UTC, eeue56 commented on index.js
> +    return [];
probably worth logging an error message as well as this

2017-03-28 22:36 UTC, sentience commented on index.js
> +    return [];
@eeue56 Done!

2017-03-29 01:10 UTC, eeue56 approved these changes

2017-03-29 01:43 UTC, sentience commented
@stoeffel Are you happy to publish this?

2017-03-29 11:31 UTC, stoeffel requested changes
@sentience LGTM, but added one last comment.

2017-03-29 11:31 UTC, stoeffel commented on index.js
> +    var elmPackage = JSON.parse(fs.readFileSync(elmPackagePath, 'utf8'));
maybe we should also check if `elmPackage` has a `source-directories` field, otherwise it will crash on line 109

2017-03-30 11:41 UTC, sentience commented on index.js
> +    var elmPackage = JSON.parse(fs.readFileSync(elmPackagePath, 'utf8'));
Agreed. All done!

2017-03-30 12:40 UTC, stoeffel approved these changes

2017-03-30 12:40 UTC, stoeffel commented on index.js
> +    console.warn('Ignored package metadata JSON file with missing/invalid source-directories: ' + elmPackagePath);
😻

2017-03-30 12:41 UTC, merged

2017-03-30 12:43 UTC, stoeffel commented
published with v1.0.1